name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
            cd /var/www/tp1ver2.yermakov.fr/
            wp --allow-root db import /var/www/tp1ver2.sql && wp --allow-root search-replace 'http://localhost/tp1ver2.yermakov.fr' 'http://tp1ver2.yermakov.fr'
            mysql -u tp1ver2 -p${{ secrets.DB_PASSWD }} tp1ver2 < /var/www/tp1ver2.sql
            wp --allow-root search-replace 'http://localhost/wordpress1tp.yermakov.fr' 'http://wordpress1tp.yermakov.fr' --skip-columns=guid
            git config --global --add safe.directory /var/www/tp1ver2.yermakov.fr
            git pull 