name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/tp1ver2.yermakov.fr/

            # Import the SQL file
            wp --allow-root db import /var/www/tp1ver2.sql

            # Run search-replace to update URLs in the database
            wp --allow-root search-replace 'http://localhost/tp1ver2.yermakov.fr' 'http://tp1ver2.yermakov.fr'

            # Clear cache (optional, depending on your setup)
            wp --allow-root cache flush

            # Update the git repository
            git config --global --add safe.directory /var/www/tp1ver2.yermakov.fr
            git pull
